### ISSUE TITLE
Zmiany kosmetyczne

### ISSUE THREAD

**Issue by zh-qs** [Cusymint/cusymint#101]
Dołączanie `+C` w wyniku całki (w `Integrate.cu`), wcześniejsze owijanie parsowanego symbolu (nie w `Solver.cu`, tylko w `CachedParser.cu`, żeby uniknąć tego, co na obrazku)

![Image](https://user-images.githubusercontent.com/91987031/201936360-93da3df0-f926-40d1-bdc7-9fbdcb468123.png)

**Comment by TortillaZHawaii** [comment]
Przydałoby się sprawdzać czy użytkownik nie wpisał znaku całki sam, np jakby chciał policzyć sumę całek `int x dx + int 1 dx` (bo chyba to jest wspierane przez silnik).
I też fajnie by było jakby nie było tylu 0 zbędnych po kropce.

**Comment by zh-qs** [comment]
Parser przepuszcza tylko jedną całkę owijającą całe wyrażenie, np `int 2x dx` jest ok, ale niepoprawna będzie suma całek albo coś w rodzaju `e^x+int x dx`
