### ISSUE TITLE
sin(x) + cos(x) + sin(x) + cos(x) się nie chce policzyć

### ISSUE THREAD

**Issue by TortillaZHawaii** [Cusymint/cusymint#124]
![image](https://user-images.githubusercontent.com/62249621/205282416-aa28d349-8d35-4d8b-98ac-a2080108c1a8.png)

**Comment by TortillaZHawaii** [comment]
![image](https://user-images.githubusercontent.com/62249621/205506196-7451d3a8-89a2-4853-835c-c36b56e54b82.png)

**Comment by zh-qs** [comment]
to jest związane z tym, że `is_function_of` jest rekurencyjne
