### ISSUE TITLE
Dystrybucja `Negation` w dodawaniach i `Reciprocal` w mnożeniach w uproszczeniach

### ISSUE THREAD

**Issue by szymon-zygula** [Cusymint/cusymint#59]
Chodzi o to, by zamieniać `Neg(a+b+c)` i `Rec(a*b*c)` na `Neg(a)+Neg(b)+Neg(c)` i analogicznie w przypadku `Reciprocal`. Potrzebne jest to, by drzewa dodawań i mnożeń dobrze się tworzyły, np. gdy mamy wyrażenie `Neg(a+b+c)+Neg(a+b+c)`. Będzie to potrzebne przy różnych uproszczeniach. Będzie częściowo dodane razem z #46.

**Comment by zh-qs** [comment]
Negacja już jest

**Comment by szymon-zygula** [comment]
Najpewniej będzie to niepotrzebne, bo i tak być może negacja i odwrotność zostaną zamienione przez `-1*` i `^-1`
